### PR TITLE
Locale fix

### PR DESCRIPTION
**Pull request by Mohamed00**
This PR implements the suggestion in davidacm/NVDA-IBMTTS-Driver#1. The Asian languages now have their locales set properly, which means that most of them will work with Trust voice's language when processing characters and symbols enabled. The exception is Japanese, however, since a lot of symbols are not preserved, which causes odd regressions, but in theory that could be solved with a custom symbols file.

### CODE REVIEW

**Comment by ultrasound1372** [comment]
Was this already being done for languages that use the latin script? I'm not entirely sure what that setting does, does it localize symbol names when navigating?

**Comment by Mohamed00** [comment]
Yes, latin-based languages worked normally. The idea behind that setting 
is that when you change languages in your synthesizer, character 
descriptions and symbols will follow along, for example enable the 
setting, switch to Spanish and type punctuation symbols. You'll notice 
that the punctuation descriptions change. This previously wasn't working 
because the Asian languages were using the wrong locale, now they do.

**Comment by tmthywynn8** [comment]
Performed the same battery of tests as found in davidacm#1, and these are the results:

1. Chinese (Mandarin):
	* Sample text: <span lang="zh">您好。我是李进。这是我的太太王燕。</span>
	* Chinese text reads fine.
	* Pausing for Chinese punctuation, e.g., 。, works as expected, even if "Trust voice's language when processing characters and symbols" is checked as it properly uses the zh_CN locale.
2. Japanese:
	* Sample text: <span lang="ja">はじめまして。私の名前は太郎です。前にお会いしたことがありますね？私の妹をご紹介しましょう。</span>
	* Japanese text reads fine.
	* Pausing for Japanese punctuation, e.g., 。 or ？, will only work if "Trust voice's language when processing characters and symbols" is unchecked, as though it properly uses the ja locale, some Japanese symbols still do not have values in the preserve field (so defaults to never)&mdash;assume all Japanese users opt for NVDA-JP.
3. Korean:
	* Sample text: <span lang="ko">안녕하십니까? 반갑습니다. 저는 한기남이라고 합니다. 한국어 기계 음성의 남자목소리라는 뜻입니다. 제 여동생을 한번 만나 보시겠습니까?</span>
	* Korean text reads fine.
	* Pausing for Korean punctuation (additional to European punctuation), e.g., ·, is inconclusive, but as it properly uses the ko locale, it should not matter if "Trust voice's language when processing characters and symbols" is checked. Note that the example Korean punctuation was not used in the sample text .
4. Character descriptions and symbols read properly for Mandarin, Japanese, and Korean if "Trust voice's language when processing characters and symbols" is checked, as the right locale is used for each of the three languages.

**Comment by Mohamed00** [comment]
I created a custom symbols file that passes the needed punctuation. The file might be a bit weird since I kind of stumbled around the interface a bit with trust voice's language enabled, so there might be some unneeded symbols, but the demo text reads properly. Revised with some more symbols I missed in the previous upload.
[symbols-ja.zip](https://github.com/ultrasound1372/NVDA-IBMTTS-Driver/files/5337661/symbols-ja.zip)

**Pull request merged**
